project:
  type: book
  output-dir: _book


lang: fr
language: 
  title-block-author-single: "Auteur"
  title-block-modified: "Dernière modification"

date-modified: last-modified
date-format: "D MMMM YYYY"

bibliography: references.bib

book:
  title: "STT-4300 - Régression II"
  #subtitle: "Rappels de régression linéaire, modèles linéaires généralisés, régression non-linéaire et non-paramétrique, modèles additifs généralisés"
  author: "Julien Miron"
  page-footer:
    left: "Notes de cours STT-4300"
    right: "Généré avec Quarto"
  repo-url: https://github.com/JulienMiron/STT-4300
  repo-actions: [edit, issue]
  sidebar:
    style: floating
    collapse-level: 1
    logo: images/logit_plot.png    # ton image, placée au-dessus du titre
  chapters:
    - index.qmd
    - 01-regression-lineaire.qmd
    - 02-regression-logistique.qmd
    - 03-modeles-lineaires-generalises.qmd
    - 04-prediction-validation-croisee.qmd
    - 05-selection-regularisation.qmd
    - 06-knn-noyau.qmd
    - 07-splines.qmd
    - 08-gam.qmd

crossref:
  chapters: true

format:
  html:
    grid:
      sidebar-width: 300px   # ta sidebar de gauche (chapitres) — défaut 250px
      margin-width: 300px    # ta TdM de droite — défaut ~200-250px selon thème
      gutter-width: 1rem   # optionnel : espace entre les colonnes
    include-in-header:
      - text: |
          <script>
          window.MathJax = {
            chtml: {
              linebreaks: { inline: false }
            },
            tex: {
              macros: {
                bb: "\\boldsymbol\\beta",
                hb: "\\hat{\\boldsymbol\\beta}",
                hv: ["\\hat{\\text V}(#1)", 1],
                hvar: ["\\widehat{\\text{Var}}(#1)", 1],
                hbj: ["\\hat\\beta_{#1}", 1],
                hpi: ["\\hat\\pi_{#1}", 1],
                heta: ["\\hat\\eta_{#1}", 1],
                hmu: ["\\hat\\mu_{#1}", 1]
              }
            }
          };
          </script>  
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: false
    smooth-scroll: true
  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: true
    keep-tex: false

editor: source

filters:
  - webr
  - filtres/titre-environnements.lua